name       : ctemplate
version    : '2.4'
release    : 3
source     :
    - https://github.com/OlafvdSpek/ctemplate/archive/ctemplate-2.4.tar.gz : ccc4105b3dc51c82b0f194499979be22d5a14504f741115be155bd991ee93cfa
license    : BSD-3-Clause
component  : programming.library
summary    : This library provides an easy to use and lightning fast text templating system to use with C++ programs.
description: |
    This library provides an easy to use and lightning fast text templating system to use with C++ programs.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share
