name       : ctemplate
version    : 2.3
release    : 1
source     :
    - git|https://github.com/OlafvdSpek/ctemplate.git : 9a1ef5f8a1d054f39ae52989cc625c8436ad4f42
license    : BSD-3-Clause
component  : programming.library
summary    : This library provides an easy to use and lightning fast text templating system to use with C++ programs.
description: |
    This library provides an easy to use and lightning fast text templating system to use with C++ programs.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share
